<?php
namespace tests\Controller;

use tests\Controller\MockControllers\ByMethodController;
use tests\Controller\MockControllers\ByRouteController;
use Tuum\Respond\Builder;
use Tuum\Respond\Helper\ReqBuilder;
use Tuum\Respond\Respond;
use Tuum\Respond\Responder;
use Zend\Diactoros\Response;

require_once __DIR__ . '/../autoloader.php';

class ControllerTest extends \PHPUnit\Framework\TestCase
{
    protected function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        Respond::setResponder(
            Responder::forge(
                Builder::forge('tuum-test')
            )->setResponse(new Response())
        );
    }

    /**
     * @test
     */
    function ByMethod_DispatchesAppropriateMethod()
    {
        $req = ReqBuilder::createFromPath('test', 'POST');
        $controller = new ByMethodController();
        $returned = $controller->test($req);
        $returned->getBody()->rewind();
        $this->assertEquals('test:post', $returned->getBody()->getContents());
    }

    /**
     * @test
     */
    function ByMethod_onGetWithParameterIsFilled()
    {
        $req = ReqBuilder::createFromPath('test', 'GET')->withQueryParams(['test' => 'filled']);
        $controller = new ByMethodController();
        $returned = $controller->test($req);
        $returned->getBody()->rewind();
        $this->assertEquals('test:filled', $returned->getBody()->getContents());
    }

    /**
     * @test
     */
    function ByMethod_optionReturnsAllow()
    {
        $req = ReqBuilder::createFromPath('test', 'OPTIONS');
        $controller = new ByMethodController();
        $returned = $controller->test($req);
        $allowed  = $returned->getHeaderLine('allow');
        $this->assertEquals('GET,OPTIONS,POST', $allowed);
    }

    /**
     * @test
     */
    function ByMethod_nonSupportedMethodReturnsNull()
    {
        $req = ReqBuilder::createFromPath('test', 'not-supported');
        $controller = new ByMethodController();
        $returned = $controller->test($req);
        $this->assertEquals(null, $returned);
    }

    /**
     * @test
     */
    function ByRoute_DispatchesMethods()
    {
        $req = ReqBuilder::createFromPath('/', 'GET');
        $controller = new ByRouteController();
        $returned = $controller->test($req);
        $returned->getBody()->rewind();
        $this->assertEquals('route:get', $returned->getBody()->getContents());

    }

    /**
     * @test
     */
    function ByRoute_DispatchesWithArgument()
    {
        $req = ReqBuilder::createFromPath('/my/tests', 'GET');
        $controller = new ByRouteController();
        $returned = $controller->test($req);
        $returned->getBody()->rewind();
        $this->assertEquals('route:tests', $returned->getBody()->getContents());
    }
    /**
     * 
     * @test
     */
    function ByRoute_optionReturnsAllow()
    {
        $req = ReqBuilder::createFromPath('/', 'OPTIONS');
        $controller = new ByRouteController();
        $returned = $controller->test($req);
        $allowed  = $returned->getHeaderLine('allow');
        $this->assertEquals('GET,HEAD,OPTIONS', $allowed);
    }

    /**
     * @test
     */
    function ByRoute_nonSupportedMethodReturnsNull()
    {
        $req = ReqBuilder::createFromPath('/', 'POST');
        $controller = new ByRouteController();
        $returned = $controller->test($req);
        $this->assertEquals(null, $returned);
    }

}